name: Swift

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  swift-build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Xcode build
      run: xcodebuild clean build -sdk iphoneos -scheme ToastUI
