name: Swift

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Xcode build
      run: |
        sudo xcode-select -s /Applications/Xcode_12.app
        xcodebuild clean build -sdk iphoneos -scheme ToastUI
